name: clever_11
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  pinput: ^5.0.1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  photo_view: ^0.15.0
  equatable: ^2.0.7
  dotted_line: ^3.2.3
  lottie: ^3.3.1
  super_tooltip: ^2.1.0
  flutter_sticky_header: ^0.7.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/images/
      - assets/json/
      - assets/lottie/

dependency_overrides:
  value_layout_builder: 0.5.0      
