// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPYnahCuJwE_pYtYcC-zNkTal6rrZVMg8',
    appId: '1:781934813010:web:df663ab33b64937659e48b',
    messagingSenderId: '781934813010',
    projectId: 'clever11',
    authDomain: 'clever11.firebaseapp.com',
    storageBucket: 'clever11.firebasestorage.app',
    measurementId: 'G-EVVL32FJFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpxK-QVv4f5VZ16IhdD_C48ae219LQbsI',
    appId: '1:781934813010:android:c3c8414de0f8d3f359e48b',
    messagingSenderId: '781934813010',
    projectId: 'clever11',
    storageBucket: 'clever11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDynCQEb66Ea7ILcKX9P4zdov99Iu8Bz7U',
    appId: '1:781934813010:ios:b0c3788c8aa28c0559e48b',
    messagingSenderId: '781934813010',
    projectId: 'clever11',
    storageBucket: 'clever11.firebasestorage.app',
    iosBundleId: 'com.example.clever11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDynCQEb66Ea7ILcKX9P4zdov99Iu8Bz7U',
    appId: '1:781934813010:ios:b0c3788c8aa28c0559e48b',
    messagingSenderId: '781934813010',
    projectId: 'clever11',
    storageBucket: 'clever11.firebasestorage.app',
    iosBundleId: 'com.example.clever11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPYnahCuJwE_pYtYcC-zNkTal6rrZVMg8',
    appId: '1:781934813010:web:3c62149d2e51a6b159e48b',
    messagingSenderId: '781934813010',
    projectId: 'clever11',
    authDomain: 'clever11.firebaseapp.com',
    storageBucket: 'clever11.firebasestorage.app',
    measurementId: 'G-ZR21W5M8SW',
  );
}
